lib/abolger_web/router.ex
defmodule AbolgerWeb.Router do
  use AbolgerWeb, :router

  import AbolgerWeb.Authorize

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug Phauxth.Remember, create_session_func: &AbolgerWeb.Auth.Utils.create_session/1

  end

  pipeline :authenticated do
    plug :user_check
  end


  pipeline :guest do
    plug :guest_check
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AbolgerWeb do
    pipe_through [:browser, :guest_check]

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/users", UserController, only: [:new, :create]


  end

  scope "/", AbolgerWeb do
    pipe_through [:browser, :authenticated]
    resources "/users", UserController, except: [:new, :create]
    resources "/sessions", SessionController, only: [:delete]
    get "/dashboard", PageController, :dashboard

    resources "/todos", TodoController do
      resources "/items", ItemController, only: [:create]
    end




  end


  # Other scopes may use custom stacks.
  # scope "/api", AbolgerWeb do
  #   pipe_through :api
  # end
end

lib/abolger_web/views/layout_view.ex
defmodule AbolgerWeb.LayoutView do
  use AbolgerWeb, :view
end

lib/abolger_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Abolger · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <li>
              <%= if @current_user do %>
             <li><%= link "Users", to: Routes.user_path(@conn, :index) %></li>
             <li><%= link @current_user.name, to: Routes.user_path(@conn, :show, @current_user) %></li>
            <li><%= link "Logout", to: Routes.session_path(@conn, :delete, @current_user), method: :delete %></li>
           <% else %>
             <li><%= link "New user", to: Routes.user_path(@conn, :new) %></li>
             <li><%= link "Login", to: Routes.session_path(@conn, :new) %></li>

           <% end %>
          <li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>