lib/abolger_web/router.ex
defmodule AbolgerWeb.Router do
  use AbolgerWeb, :router

  import AbolgerWeb.Authorize

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug Phauxth.Remember, create_session_func: &AbolgerWeb.Auth.Utils.create_session/1

  end

  pipeline :authenticated do
    plug :user_check
  end


  pipeline :guest do
    plug :guest_check
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AbolgerWeb do
    pipe_through [:browser, :guest_check]

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create]
    resources "/users", UserController, only: [:new, :create]


  end

  scope "/", AbolgerWeb do
    pipe_through [:browser, :authenticated]
    resources "/users", UserController, except: [:new, :create]
    resources "/sessions", SessionController, only: [:delete]
    get "/dashboard", PageController, :dashboard

    resources "/todos", TodoController do
      resources "/items", ItemController, only: [:create]
    end




  end


  # Other scopes may use custom stacks.
  # scope "/api", AbolgerWeb do
  #   pipe_through :api
  # end
end

lib/abolger/todos/todo.ex
defmodule Abolger.Todos.Todo do
  use Ecto.Schema
  import Ecto.Changeset

  alias Abolger.Repo


  alias Abolger.Accounts.User
  alias Abolger.Items.Item

  schema "todos" do
    field :todo, :string
    belongs_to :user, User
    has_many :items, Item

    timestamps()
  end

  def changeset(todo, attrs) do
    todo
    |> cast(attrs, [:todo,  :user_id])
    |> validate_required([:todo])
  end


end

lib/abolger_web/controllers/todo_controller.ex
defmodule AbolgerWeb.TodoController do
  use AbolgerWeb, :controller

  alias Abolger.Todos.Todo
  alias Abolger.Repo
  alias Abolger.Accounts.User
  alias Abolger.Todohandler
  alias Abolger.Items
  alias Abolger.Items.Item


    def index(conn, _params) do
      todo = Todohandler.list_todos()
      render(conn, "index.html", todos: todo)
    end


    def show(conn, %{"id" => id}) do
      todo = Todohandler.get_todo!(id)
      items = Items.change_item(%Item{})
      render(conn, "show.html", todo: todo, items: items)
    end


      def new(conn, _params) do
        changeset = Todohandler.change_todo(%Todo{})

        render(conn, "new.html", changeset: changeset)
      end


      def create(conn, %{"todo" => todo_params}) do

            case Todohandler.create_todo(conn.assigns.current_user, todo_params) do
              {:ok, _comment} ->
                conn
                |> put_flash(:info, "Todo created successfully.")
                |> redirect(to: Routes.todo_path(conn, :index))
              {:error, _changeset} ->
                conn
                |> put_flash(:error, "Issue creating todo.")
                |> redirect(to: Routes.todo_path(conn, :index))
            end
      end


      # def create(conn, %{"todo" => todo}) do
      #   # changeset = Todo.changeset(%Todo{}, todo)
      #   IO.inspect(conn.assigns.current_user)
      #   changeset =
      #    conn.assigns.current_user
      #     |> Ecto.build_assoc(:todos)
      #     |> Todo.changeset(todo)

      #   case Repo.insert(changeset) do
      #     {:ok, _} ->
      #       conn
      #       |> put_flash(:info, "Todo Created")
      #       |> redirect(to: Routes.todo_path(conn, :index))

      #     {:error, changeset} ->
      #       render(conn, "new.html", changeset: changeset)
      #   end
      # end

      def edit(conn, %{"id" => todo_id}) do
        todo = Repo.get(Todo, todo_id)
        changeset = Todo.changeset(todo)
        render(conn, "edit.html", changeset: changeset, todo: todo)
      end

      def update(conn, %{"id" => todo_id, "todo" => todo}) do
        old_todo = Repo.get(Todo, todo_id)
        changeset = Todo.changeset(old_todo, todo)

        # changeset = Repo.get(Todo, todo_id) |> Todo.changeset(todo)
        case Repo.update(changeset) do
          {:ok, _todo} ->
            conn
            |> put_flash(:info, "Todo Updated")
            |> redirect(to: Routes.todo_path(conn, :index))

          {:error, changeset} ->
            render(conn, "edit.html", changeset: changeset, todo: old_todo)
        end
      end

      def delete(conn, %{"id" => todo_id}) do
        Repo.get!(Todo, todo_id) |> Repo.delete!()

        conn
        |> put_flash(:info, "Todo Deleted")
        |> redirect(to: Routes.todo_path(conn, :index))
      end

      def check_todo_owner(conn, _params) do
        %{params: %{"id" => todo_id}} = conn

        if Repo.get(Todo, todo_id).user_id == conn.assigns.current_user do
          conn
        else
          conn
          |> put_flash(:error, "Your cannot edit that")
          |> redirect(to: Routes.todo_path(conn, :index))
          |> halt()
        end
      end
    end

lib/abolger_web/views/todo_view.ex
defmodule AbolgerWeb.TodoView do
  use AbolgerWeb, :view
end

lib/abolger_web/templates/todo/edit.html.eex
<h1>Edit Todo</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :update, @todo)) %>

<span><%= link "Back", to: Routes.todo_path(@conn, :index) %></span>

lib/abolger_web/templates/todo/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :todo %>
  <%= text_input f, :todo %>
  <%= error_tag f, :todo %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/abolger_web/templates/todo/index.html.eex
<h1>Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th>Todo</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for todo <- @todos do %>
    <tr>
      <td><%= todo.todo %></td>

      <td>
        <%= link "Show", to: Routes.todo_path(@conn, :show, todo) %>
        <%= link "Edit", to: Routes.todo_path(@conn, :edit, todo) %>
        <%= link "Delete", to: Routes.todo_path(@conn, :delete, todo), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Todo", to: Routes.todo_path(@conn, :new) %></span>

lib/abolger_web/templates/todo/new.html.eex
<h1>New Todo</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.todo_path(@conn, :index) %></span>

lib/abolger_web/templates/todo/show.html.eex
<h1>Show Todo</h1>

<ul>

  <li>
    <strong>Todo:</strong>
    <%= @todo.todo %>
  </li>

</ul>
<ul>
<%= for items <- @todo.items do %>
  <li class="comment"><%= items.item %></li>
<% end %>
</ul>

<h3>Add a Item</h3>
<%= form_for @items, Routes.todo_item_path(@conn, :create, @todo), fn f -> %>
  <%= label f, :item %>
  <%= textarea f, :item %>
  <%= error_tag f, :item %>
  <div>
    <%= submit "Save" %>
  </div>
<% end %>


<span><%= link "Edit", to: Routes.todo_path(@conn, :edit, @todo) %></span>
<span><%= link "Back", to: Routes.todo_path(@conn, :index) %></span>